services:
#  authorizationserver.api:
#    image: authorizationserver.api
#    depends_on:
#      - sqlserver
#    build:
#      context: .
#      dockerfile: AuthorizationServer.API/Dockerfile
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"